# Generated by Django 4.1.3 on 2023-03-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_task_file_taskfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
