# Generated by Django 4.1.3 on 2023-03-17 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
