# Generated by Django 4.1.3 on 2023-03-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_alter_action_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
    ]
