# Generated by Django 4.1.3 on 2023-02-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='twoFACode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2FA Code'),
        ),
    ]
