# Generated by Django 4.1.3 on 2023-03-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_status_type'),
        ('account', '0002_instagram_twofacode'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_accounts', to='workspace.status', verbose_name='Status'),
        ),
    ]
