# Generated by Django 4.1.3 on 2023-03-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_instagram_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='instagram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_platforms', to='account.instagram'),
        ),
    ]
