# Generated by Django 4.1.3 on 2023-03-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_socialplatform_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='session ID'),
        ),
    ]
