# Generated by Django 4.1.3 on 2023-02-27 08:30

import ckeditor.fields
from django.db import migrations, models
import workspace.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=150, verbose_name='Referans Nömrəsi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
            bases=(models.Model, workspace.mixins.JSONFieldModelMixin),
        ),
        migrations.CreateModel(
            name='NotifyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_obj_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Notify object id')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('email_subject', models.CharField(max_length=150, verbose_name='Email subject')),
                ('email_text', ckeditor.fields.RichTextField()),
                ('web_text', models.TextField(blank=True, max_length=500, verbose_name='Web text')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Notifications enabled')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, workspace.mixins.JSONFieldModelMixin),
        ),
    ]
